name: Docs

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install package with docs dependencies
        run: |
          pip install -e .[docs]
      - name: Build and deploy documentation
        run: |
          mkdocs gh-deploy --force